services:
  php:
    build: ./docker/php
    container_name: challenge_php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: shopping_cart
      DB_USER: shopping
      DB_PASSWORD: CarT01

  nginx:
    image: nginx:latest
    container_name: challenge_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: challenge_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopping_cart
      MYSQL_USER: shopping
      MYSQL_PASSWORD: CarT01
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  composer:
    container_name: challenge-composer
    build:
      context: ./docker/composer
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    command: ["composer", "install"]

  memcached:
    image: memcached:1.6
    container_name: challenge_memcached
    ports:
      - "11211:11211"

volumes:
  db_data:
