doctrine:
    dbal:
        driver: '%env(DB_DRIVER)%'
        host: '%env(DB_HOST)%'
        port: '%env(DB_PORT)%'
        dbname: '%env(DB_NAME)%'
        user: '%env(DB_USER)%'
        password: '%env(DB_PASSWORD)%'
        charset: '%env(DB_CHARSET)%'
        server_version: '%env(DB_VERSION)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: false
        mappings:
            ChallengeInfrastructure:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/ShoppingCartContext/Infrastructure/Persistence/Doctrine/Entity'
                prefix: 'Challenge\ShoppingCartContext\Infrastructure\Persistence\Doctrine\Entity'
                alias: ChallengePersistence

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
