# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Challenge\:
        resource: '%kernel.project_dir%/src/'

    Challenge\Api\:
        resource: '%kernel.project_dir%/api/'
        exclude:
            - '%kernel.project_dir%/api/Resources/ChallengeApiKernel.php'
            - '%kernel.project_dir%/api/Resources/config/**'
        tags: ['controller.service_arguments']

    tactician_query_handlers:
        namespace: Challenge\
        resource: '%kernel.project_dir%/src/**/*Handler.php'
        tags:
          - { name: tactician.handler, typehints: true }

    Challenge\Api\Controller\:
        namespace: Challenge\Api\Controller\
        resource: '%kernel.project_dir%/api/Controller/*Controller.php'
        tags: ['controller.service_arguments']